# Install the latest Android APK generated by Tauri/Gradle.
param(
    [switch]$Release,
    [switch]$Debug,
    [switch]$Clean
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$ApkRoot = Join-Path $Root "src-tauri\gen\android\app\build\outputs\apk"
$PackageName = "com.vpn.tauri"

function Assert-Adb {
    $adb = Get-Command adb -ErrorAction SilentlyContinue
    if (-not $adb) {
        throw "未找到 adb，请先安装 Android Platform Tools，并确认 adb 已加入 PATH"
    }
}

function Get-LatestApk {
    if ($Release) {
        $patterns = @("*release-debugsigned.apk", "*release*.apk")
    } elseif ($Debug) {
        $patterns = @("*debug*.apk")
    } else {
        $patterns = @("*release-debugsigned.apk", "*debug*.apk", "*release*.apk")
    }

    foreach ($pattern in $patterns) {
        $apk = Get-ChildItem -Path $ApkRoot -Recurse -Filter $pattern -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -notmatch "unsigned" } |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
        if ($apk) { return $apk }
    }
    return $null
}

Assert-Adb

$apk = Get-LatestApk
if (-not $apk) {
    if ($Release) {
        throw "未找到可安装 Release APK，请先运行 npm run tauri:android:build:release"
    }
    throw "未找到可安装 APK，请先运行 npm run tauri:android:build 或 npm run tauri:android:build:release"
}

if ($Clean) {
    Write-Host "Uninstalling $PackageName if present..."
    cmd /c "adb uninstall $PackageName"
}

$sizeMb = [math]::Round($apk.Length / 1MB, 1)
Write-Host "Installing APK: $($apk.FullName) ($sizeMb MB)"
cmd /c "adb install -r `"$($apk.FullName)`""
if ($LASTEXITCODE -ne 0) {
    throw "adb install failed；如果提示签名不一致，请运行：npm run tauri:android:install:release:clean"
}

Write-Host "Installed $PackageName successfully"
