[package]
name = "vpn-tauri"
version = "1.2.4"
description = "跨云 Tauri 跨端客户端"
authors = ["vpn"]
edition = "2021"

[lib]
name = "vpn_tauri_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
which = "7"
if-addrs = "0.13"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
windows-sys = { version = "0.59", features = ["Win32_Networking_WinInet"] }
